import fs from "node:fs";
import path from "node:path";

const inputPath = path.join("src", "data", "series.tsv");
const outputPath = path.join("src", "data", "series.generated.ts");

const requiredHeaders = ["title"];

function fail(message) {
  console.error(`series.tsv: ${message}`);
  process.exit(1);
}

function ensure(condition, message) {
  if (!condition) fail(message);
}

function parseOptionalBoolean(value, label) {
  if (!value) return undefined;
  if (/^(true|1|yes|y)$/i.test(value)) return true;
  if (/^(false|0|no|n)$/i.test(value)) return false;
  fail(`${label} must be true/false.`);
}

function parseOptionalNumber(value, label) {
  if (!value) return undefined;
  const parsed = Number(value);
  ensure(Number.isFinite(parsed), `${label} must be a valid number.`);
  return parsed;
}

function normalizeHeaderName(name) {
  return name.trim().replace(/^\uFEFF/, "").toLowerCase();
}

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const raw = fs.readFileSync(inputPath, "utf8");
const lines = raw.split(/\r?\n/).filter((line) => line.trim().length > 0);

ensure(lines.length >= 1, "missing header row.");

const headers = lines[0].split("\t").map((header) => normalizeHeaderName(header));
const headerIndex = Object.fromEntries(headers.map((header, index) => [header, index]));
const aliases = {
  id: ["id_slug", "slugid", "slug_id", "slug", "id"],
  coverCaseId: ["covercaseid", "cover_case_id", "coverid"],
  showOnHome: ["showonhome", "show_on_home", "show"],
  homeOrder: ["homeorder", "home_order"],
};

const missingHeaders = requiredHeaders.filter(
  (header) => headerIndex[normalizeHeaderName(header)] === undefined,
);
ensure(missingHeaders.length === 0, `missing headers: ${missingHeaders.join(", ")}`);
ensure(
  aliases.id.some((name) => headerIndex[name] !== undefined),
  "missing id column: expected id_slug (or slugID/id).",
);

const seenIds = new Set();
const series = [];

for (let i = 1; i < lines.length; i += 1) {
  const lineNumber = i + 1;
  const cells = lines[i].split("\t", -1);
  const get = (name) => {
    const index = headerIndex[normalizeHeaderName(name)];
    return index === undefined ? "" : (cells[index] ?? "").trim();
  };
  const getAny = (names) => {
    for (const name of names) {
      const value = get(name);
      if (value) return value;
    }
    return "";
  };

  const fallbackNumber = i;
  const titleRaw = get("title");
  const title = titleRaw || `Untitled Series ${fallbackNumber}`;
  const idRaw = getAny(aliases.id);
  const idFromTitle = slugify(title);
  const idBase = idRaw || idFromTitle || `series-${fallbackNumber}`;
  let id = idBase;
  let duplicateSuffix = 2;
  while (seenIds.has(id)) {
    id = `${idBase}-${duplicateSuffix}`;
    duplicateSuffix += 1;
  }

  const description = get("description") || "Series description coming soon.";
  const coverCaseId = getAny(aliases.coverCaseId);
  const showOnHome = parseOptionalBoolean(
    getAny(aliases.showOnHome),
    `line ${lineNumber}: showOnHome`,
  );
  const homeOrder = parseOptionalNumber(
    getAny(aliases.homeOrder),
    `line ${lineNumber}: homeOrder`,
  );

  seenIds.add(id);
  const entry = { id, title };
  entry.description = description;
  if (coverCaseId) entry.coverCaseId = coverCaseId;
  entry.showOnHome = showOnHome ?? true;
  entry.homeOrder = homeOrder ?? fallbackNumber;

  series.push(entry);
}

const output = [
  "// Generated by scripts/gen-series.mjs. Do not edit directly.",
  'import type { Series } from "./series";',
  "",
  `export const SERIES: Series[] = ${JSON.stringify(series, null, 2)};`,
  "",
].join("\n");

fs.writeFileSync(outputPath, output, "utf8");
