import fs from "node:fs";
import path from "node:path";

const inputPath = path.join("src", "data", "cases.tsv");
const outputPath = path.join("src", "data", "cases.generated.ts");

const requiredHeaders = [
  "id",
  "title",
  "subtitle",
  "roles",
  "copy",
  "tags",
  "youtubeId",
  "href",
  "mediaKind",
  "mediaSrc",
  "mediaAlt",
  "mediaPoster",
  "stripSources",
];

function fail(message) {
  console.error(`cases.tsv: ${message}`);
  process.exit(1);
}

function ensure(condition, message) {
  if (!condition) fail(message);
}

const raw = fs.readFileSync(inputPath, "utf8");
const lines = raw.split(/\r?\n/).filter((line) => line.trim().length > 0);

ensure(lines.length > 1, "no data rows found.");

const headers = lines[0].split("\t").map((header) => header.trim());
const headerIndex = Object.fromEntries(headers.map((header, index) => [header, index]));

const missingHeaders = requiredHeaders.filter((header) => headerIndex[header] === undefined);
ensure(missingHeaders.length === 0, `missing headers: ${missingHeaders.join(", ")}`);

const seenIds = new Set();
const cases = [];

for (let i = 1; i < lines.length; i += 1) {
  const lineNumber = i + 1;
  const cells = lines[i].split("\t");
  const get = (name) => (cells[headerIndex[name]] ?? "").trim();

  const id = get("id");
  const title = get("title");
  const subtitle = get("subtitle");
  const roles = get("roles");
  const copy = get("copy");
  const tagsRaw = get("tags");
  const youtubeId = get("youtubeId");
  const hrefRaw = get("href");
  const mediaKind = get("mediaKind");
  const mediaSrcRaw = get("mediaSrc");
  const mediaAltRaw = get("mediaAlt");
  const mediaPoster = get("mediaPoster");
  const stripSourcesRaw = get("stripSources");

  ensure(id, `line ${lineNumber}: id is required.`);
  ensure(!seenIds.has(id), `line ${lineNumber}: duplicate id "${id}".`);
  seenIds.add(id);

  ensure(title, `line ${lineNumber}: title is required.`);
  ensure(roles, `line ${lineNumber}: roles is required.`);
  ensure(tagsRaw, `line ${lineNumber}: tags is required.`);
  ensure(mediaKind, `line ${lineNumber}: mediaKind is required.`);

  const tags = tagsRaw
    .split("|")
    .map((tag) => tag.trim())
    .filter(Boolean);
  ensure(tags.length > 0, `line ${lineNumber}: tags must include at least one entry.`);

  const href = hrefRaw || (youtubeId ? `https://www.youtube.com/watch?v=${youtubeId}` : "");

  let media;
  if (mediaKind === "image") {
    const src = mediaSrcRaw || (youtubeId ? `https://i.ytimg.com/vi/${youtubeId}/hqdefault.jpg` : "");
    ensure(src, `line ${lineNumber}: mediaSrc is required for image without youtubeId.`);
    const alt = mediaAltRaw || `${title} thumbnail`;
    media = { kind: "image", src, alt };
  } else if (mediaKind === "video") {
    ensure(mediaSrcRaw, `line ${lineNumber}: mediaSrc is required for video.`);
    media = { kind: "video", src: mediaSrcRaw };
    if (mediaPoster) {
      media.poster = mediaPoster;
    }
  } else if (mediaKind === "strip") {
    const sources = stripSourcesRaw
      .split("|")
      .map((source) => source.trim())
      .filter(Boolean);
    ensure(sources.length > 0, `line ${lineNumber}: stripSources is required for strip media.`);
    media = { kind: "strip", sources };
  } else {
    fail(`line ${lineNumber}: unsupported mediaKind "${mediaKind}".`);
  }

  const entry = { id, title, roles, tags, media };

  if (subtitle) entry.subtitle = subtitle;
  if (copy) entry.copy = copy;
  if (youtubeId) entry.youtubeId = youtubeId;
  if (href) entry.href = href;

  cases.push(entry);
}

const output = [
  "// Generated by scripts/gen-cases.mjs. Do not edit directly.",
  'import type { Case } from "./cases";',
  "",
  `export const CASES: Case[] = ${JSON.stringify(cases, null, 2)};`,
  "",
].join("\n");

fs.writeFileSync(outputPath, output, "utf8");
