// Generated by scripts/gen-cases.mjs. Do not edit directly.
import type { Case } from "./cases";

export const CASES: Case[] = [
  {
    "id": "rebirthing-center",
    "title": "The Rebirthing Center",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/BXOaAgDnpd8/hqdefault.jpg",
      "alt": "The Rebirthing Center thumbnail"
    },
    "copy": "Webby-nominated short for Comedy Central Digital.",
    "youtubeId": "BXOaAgDnpd8",
    "href": "https://www.youtube.com/watch?v=BXOaAgDnpd8"
  },
  {
    "id": "polyamorous-romcom",
    "title": "The Polyamorous RomCom",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/XhMz5vRlya8/hqdefault.jpg",
      "alt": "The Polyamorous RomCom thumbnail"
    },
    "subtitle": "ft. Yung Gravy",
    "copy": "Comedy Central Digital sketch collaboration.",
    "youtubeId": "XhMz5vRlya8",
    "href": "https://www.youtube.com/watch?v=XhMz5vRlya8"
  },
  {
    "id": "remote-control-boss",
    "title": "Remote Control Boss",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/2PPkDxOul_0/hqdefault.jpg",
      "alt": "Remote Control Boss thumbnail"
    },
    "copy": "Comedy Central Digital character-driven sketch.",
    "youtubeId": "2PPkDxOul_0",
    "href": "https://www.youtube.com/watch?v=2PPkDxOul_0"
  },
  {
    "id": "litterbox-office",
    "title": "The Litterbox Office",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "viral"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/KIdN_iYBW7A/hqdefault.jpg",
      "alt": "The Litterbox Office thumbnail"
    },
    "copy": "500M+ views comedy concept.",
    "youtubeId": "KIdN_iYBW7A",
    "href": "https://www.youtube.com/watch?v=KIdN_iYBW7A"
  },
  {
    "id": "icontact",
    "title": "iContact",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/aQN6jBk_LWc/hqdefault.jpg",
      "alt": "iContact thumbnail"
    },
    "subtitle": "ft. DeStorm",
    "copy": "Comedy Central Digital collaboration.",
    "youtubeId": "aQN6jBk_LWc",
    "href": "https://www.youtube.com/watch?v=aQN6jBk_LWc"
  },
  {
    "id": "living-funeral-home",
    "title": "The Living Funeral Home",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/zcqkqql5VW0/hqdefault.jpg",
      "alt": "The Living Funeral Home thumbnail"
    },
    "subtitle": "ft. Lala Milan",
    "copy": "High-concept social comedy short.",
    "youtubeId": "zcqkqql5VW0",
    "href": "https://www.youtube.com/watch?v=zcqkqql5VW0"
  },
  {
    "id": "teen-uncle",
    "title": "Teen Uncle",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/YUJIjQ0MytM/hqdefault.jpg",
      "alt": "Teen Uncle thumbnail"
    },
    "subtitle": "ft. Adam Waheed",
    "copy": "Comedy Central Digital talent collaboration.",
    "youtubeId": "YUJIjQ0MytM",
    "href": "https://www.youtube.com/watch?v=YUJIjQ0MytM"
  },
  {
    "id": "whameo",
    "title": "Whameo",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/GBG1KLVBQPA/hqdefault.jpg",
      "alt": "Whameo thumbnail"
    },
    "subtitle": "ft. Sven Johnson",
    "copy": "Comedy Central Digital sketch piece.",
    "youtubeId": "GBG1KLVBQPA",
    "href": "https://www.youtube.com/watch?v=GBG1KLVBQPA"
  },
  {
    "id": "take-a-deep-breath",
    "title": "Take a Deep F***ing Breath",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/2Z4VgVKrveM/hqdefault.jpg",
      "alt": "Take a Deep F***ing Breath thumbnail"
    },
    "copy": "Comedy Central Originals short.",
    "youtubeId": "2Z4VgVKrveM",
    "href": "https://www.youtube.com/watch?v=2Z4VgVKrveM"
  },
  {
    "id": "freezing-your-eggs",
    "title": "Freezing Your Eggs",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/DJCgT1gw8nc/hqdefault.jpg",
      "alt": "Freezing Your Eggs thumbnail"
    },
    "copy": "Comedy Central Originals sketch.",
    "youtubeId": "DJCgT1gw8nc",
    "href": "https://www.youtube.com/watch?v=DJCgT1gw8nc"
  },
  {
    "id": "vesting-up",
    "title": "Vesting Up",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/gSojwTO5QZs/hqdefault.jpg",
      "alt": "Vesting Up thumbnail"
    },
    "copy": "Comedy Central Originals production.",
    "youtubeId": "gSojwTO5QZs",
    "href": "https://www.youtube.com/watch?v=gSojwTO5QZs"
  },
  {
    "id": "rich-friend",
    "title": "Rich Friend",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/lQankmO_xbQ/hqdefault.jpg",
      "alt": "Rich Friend thumbnail"
    },
    "subtitle": "ft. Anwar",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "lQankmO_xbQ",
    "href": "https://www.youtube.com/watch?v=lQankmO_xbQ"
  },
  {
    "id": "she-looks-like-her-dad",
    "title": "She Looks Like Her Dad",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/oCYzAHPMTUM/hqdefault.jpg",
      "alt": "She Looks Like Her Dad thumbnail"
    },
    "subtitle": "ft. DeStorm",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "oCYzAHPMTUM",
    "href": "https://www.youtube.com/watch?v=oCYzAHPMTUM"
  },
  {
    "id": "staying-young-forever",
    "title": "Staying Young Forever",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/bFYFLfq6nZo/hqdefault.jpg",
      "alt": "Staying Young Forever thumbnail"
    },
    "subtitle": "ft. Lala Milan",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "bFYFLfq6nZo",
    "href": "https://www.youtube.com/watch?v=bFYFLfq6nZo"
  },
  {
    "id": "nothing-gay-in-the-wild-west",
    "title": "Nothing Gay in the Wild West",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/uE1Y7PHMdPc/hqdefault.jpg",
      "alt": "Nothing Gay in the Wild West thumbnail"
    },
    "subtitle": "ft. Brooks Allison",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "uE1Y7PHMdPc",
    "href": "https://www.youtube.com/watch?v=uE1Y7PHMdPc"
  },
  {
    "id": "andys-roadshow",
    "title": "Andy's Roadshow",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-sketches",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/iLNypL04zH0/hqdefault.jpg",
      "alt": "Andy's Roadshow thumbnail"
    },
    "copy": "Original sketch content.",
    "youtubeId": "iLNypL04zH0",
    "href": "https://www.youtube.com/watch?v=iLNypL04zH0"
  },
  {
    "id": "tuber",
    "title": "Tuber",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-sketches",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/0U5SCBko2XM/hqdefault.jpg",
      "alt": "Tuber thumbnail"
    },
    "copy": "Original sketch content.",
    "youtubeId": "0U5SCBko2XM",
    "href": "https://www.youtube.com/watch?v=0U5SCBko2XM"
  },
  {
    "id": "beauty-and-the-bowl",
    "title": "Beauty and the Bowl",
    "roles": "Director, Cinematographer, & Editor",
    "tags": [
      "comedy-sketches",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/RhzSqWrjx7Q/hqdefault.jpg",
      "alt": "Beauty and the Bowl thumbnail"
    },
    "subtitle": "ft. Uncle Function",
    "copy": "Sketch comedy featured on Funny Or Die.",
    "youtubeId": "RhzSqWrjx7Q",
    "href": "https://www.youtube.com/watch?v=RhzSqWrjx7Q"
  },
  {
    "id": "poly-bachelorette",
    "title": "Poly Bachelorette",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-sketches",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/PEwfwxtwkWE/hqdefault.jpg",
      "alt": "Poly Bachelorette thumbnail"
    },
    "copy": "Original sketch content.",
    "youtubeId": "PEwfwxtwkWE",
    "href": "https://www.youtube.com/watch?v=PEwfwxtwkWE"
  },
  {
    "id": "grandmothers-announcement",
    "title": "Grandmother's Announcement",
    "roles": "Director, Cinematographer, & Editor",
    "tags": [
      "comedy-sketches",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/qSPdMoxsZoU/hqdefault.jpg",
      "alt": "Grandmother's Announcement thumbnail"
    },
    "copy": "Written by Lulu Krause.",
    "youtubeId": "qSPdMoxsZoU",
    "href": "https://www.youtube.com/watch?v=qSPdMoxsZoU"
  },
  {
    "id": "settling",
    "title": "Settling",
    "roles": "Co-Director, Cinematographer, & Editor",
    "tags": [
      "comedy-sketches",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/qhXZjxXbW4s/hqdefault.jpg",
      "alt": "Settling thumbnail"
    },
    "copy": "Featuring Gianmarco Soresi & Megan Sass.",
    "youtubeId": "qhXZjxXbW4s",
    "href": "https://www.youtube.com/watch?v=qhXZjxXbW4s"
  },
  {
    "id": "snapchat",
    "title": "Making It",
    "roles": "Director, Cinematographer, & Editor",
    "tags": [
      "snapchat",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://placehold.co/640x360",
      "alt": "Comedy Central Collage"
    },
    "copy": "As Director, Cinematographer, and Editor, Andy brought an original vertical series to life for Snapchat's Snap Originals."
  },
  {
    "id": "rizzle-asian-comedy-fest",
    "title": "Rizzle's Asian Comedy Fest",
    "roles": "Director & Editor",
    "tags": [
      "rizzle",
      "award"
    ],
    "media": {
      "kind": "strip",
      "sources": [
        "/videos/rizzle1.mp4",
        "/videos/rizzle2.mp4",
        "/videos/rizzle3.mp4"
      ]
    },
    "copy": "$1000 Grand Prize winner for a new vertical series!"
  },
  {
    "id": "architects-newspaper-interviews",
    "title": "Architect's Newspaper",
    "roles": "Videographer & Editor",
    "tags": [
      "architecture",
      "interview-series"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/Bzhb1WBUNps/hqdefault.jpg",
      "alt": "Architect's Newspaper thumbnail"
    },
    "subtitle": "Interview Series",
    "copy": "Videographer and editor for interviews on new architecture projects.",
    "youtubeId": "Bzhb1WBUNps",
    "href": "https://www.youtube.com/watch?v=Bzhb1WBUNps"
  },
  {
    "id": "barkbox-socials",
    "title": "BarkBox Socials",
    "roles": "DP & Editor",
    "tags": [
      "branded",
      "social-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/5_Ls6uFv02c/hqdefault.jpg",
      "alt": "BarkBox Socials thumbnail"
    },
    "copy": "Cinematographer and editor for social video campaigns for BarkBox.",
    "youtubeId": "5_Ls6uFv02c",
    "href": "https://www.youtube.com/watch?v=5_Ls6uFv02c"
  },
  {
    "id": "death-becomes-her",
    "title": "Death Becomes Her: The Musical",
    "roles": "Director, Producer, & Editor",
    "tags": [
      "branded",
      "social-campaign"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/gvjDOk8T9Lo/hqdefault.jpg",
      "alt": "Death Becomes Her: The Musical thumbnail"
    },
    "copy": "Director, producer, and editor for the show's social campaign.",
    "youtubeId": "gvjDOk8T9Lo",
    "href": "https://www.youtube.com/watch?v=gvjDOk8T9Lo"
  },
  {
    "id": "election-science-duvergers-law",
    "title": "Duverger's Law",
    "roles": "Producer, Writer, & Editor",
    "tags": [
      "nonprofit",
      "explainer"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/HpBRGXK-QNs/hqdefault.jpg",
      "alt": "Duverger's Law thumbnail"
    },
    "subtitle": "Center for Election Science",
    "copy": "Volunteer explainer developed with Election Science experts.",
    "youtubeId": "HpBRGXK-QNs",
    "href": "https://www.youtube.com/watch?v=HpBRGXK-QNs"
  },
  {
    "id": "illuminative-voting-campaign",
    "title": "Illuminative Voting Campaign",
    "roles": "Editor",
    "tags": [
      "nonprofit",
      "campaign"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/vpQ71ynCHco/hqdefault.jpg",
      "alt": "Illuminative Voting Campaign thumbnail"
    },
    "copy": "Edited campaign videos with Center for Media & Social Impact.",
    "youtubeId": "vpQ71ynCHco",
    "href": "https://www.youtube.com/watch?v=vpQ71ynCHco"
  },
  {
    "id": "movement-royal-heart",
    "title": "Royal Heart",
    "roles": "Cinematographer & Editor",
    "tags": [
      "movement",
      "dance"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/zG2amIyE1Es/hqdefault.jpg",
      "alt": "Royal Heart thumbnail"
    },
    "subtitle": "Movement & Dance",
    "copy": "Movement short choreographed by Hayden Frederick.",
    "youtubeId": "zG2amIyE1Es",
    "href": "https://www.youtube.com/watch?v=zG2amIyE1Es"
  },
  {
    "id": "instagram-betches",
    "title": "Instagram Betches",
    "roles": "Director & Cinematographer",
    "tags": [
      "music-video",
      "comedy"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/hQO_LLV9tms/hqdefault.jpg",
      "alt": "Instagram Betches thumbnail"
    },
    "copy": "Winner of Best Sketch at NYC Short Comedy Film Fest 2020.",
    "youtubeId": "hQO_LLV9tms",
    "href": "https://www.youtube.com/watch?v=hQO_LLV9tms"
  },
  {
    "id": "securocam-3000",
    "title": "Securocam 3000",
    "roles": "Director, Co-Writer, & Editor",
    "tags": [
      "webseries",
      "comedy"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/_SRIskz2JOY/hqdefault.jpg",
      "alt": "Securocam 3000 thumbnail"
    },
    "copy": "Co-created short web series selected by NYTVF and IFC Comedy Crib.",
    "youtubeId": "_SRIskz2JOY",
    "href": "https://www.youtube.com/watch?v=_SRIskz2JOY"
  },
  {
    "id": "operators",
    "title": "Operators",
    "roles": "Director, Co-Writer, & Co-Editor",
    "tags": [
      "short-film",
      "festival"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/aa2zI7PO-X8/hqdefault.jpg",
      "alt": "Operators thumbnail"
    },
    "copy": "Nevermore Film Fest 2024 short co-created with Katie Sicking.",
    "youtubeId": "aa2zI7PO-X8",
    "href": "https://www.youtube.com/watch?v=aa2zI7PO-X8"
  },
  {
    "id": "spoilednyc-dickpicr",
    "title": "DickPicr",
    "roles": "Director, Cinematographer, & Editor",
    "tags": [
      "web-series",
      "comedy"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/eUfz8WSA5wI/hqdefault.jpg",
      "alt": "DickPicr thumbnail"
    },
    "subtitle": "SpoiledNYC",
    "copy": "Sketch from the SpoiledNYC comedy collaborations.",
    "youtubeId": "eUfz8WSA5wI",
    "href": "https://www.youtube.com/watch?v=eUfz8WSA5wI"
  },
  {
    "id": "tech-videos-showreel",
    "title": "Tech Videos Showreel",
    "roles": "Director & Technologist",
    "tags": [
      "tech",
      "creative-coding"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/bpkZSxtZd7Y/hqdefault.jpg",
      "alt": "Tech Videos Showreel thumbnail"
    },
    "copy": "Experiments documenting interactive and 3D production pipelines.",
    "youtubeId": "bpkZSxtZd7Y",
    "href": "https://www.youtube.com/watch?v=bpkZSxtZd7Y"
  },
  {
    "id": "honest-waitress",
    "title": "The Honest Waitress",
    "roles": "Director",
    "tags": [
      "webseries",
      "comedy"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/zlFyjWf4hOk/hqdefault.jpg",
      "alt": "The Honest Waitress thumbnail"
    },
    "copy": "Short comedy series for PitTV written by Leila Graham.",
    "youtubeId": "zlFyjWf4hOk",
    "href": "https://www.youtube.com/watch?v=zlFyjWf4hOk"
  },
  {
    "id": "westbrook-studios",
    "title": "Westbrook Studios",
    "roles": "Editor",
    "tags": [
      "brand-studio",
      "social-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/_NiN2zU79is/hqdefault.jpg",
      "alt": "Westbrook Studios thumbnail"
    },
    "copy": "Freelance editor on social content for Westbrook Studios.",
    "youtubeId": "_NiN2zU79is",
    "href": "https://www.youtube.com/watch?v=_NiN2zU79is"
  }
];
