// Generated by scripts/gen-cases.mjs. Do not edit directly.
import type { Case } from "./cases";

export const CASES: Case[] = [
  {
    "id": "rebirthing-center",
    "title": "The Rebirthing Center",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/BXOaAgDnpd8/hqdefault.jpg",
      "alt": "The Rebirthing Center thumbnail"
    },
    "copy": "Webby-nominated short for Comedy Central Digital.",
    "youtubeId": "BXOaAgDnpd8",
    "href": "https://www.youtube.com/watch?v=BXOaAgDnpd8"
  },
  {
    "id": "polyamorous-romcom",
    "title": "The Polyamorous RomCom",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/XhMz5vRlya8/hqdefault.jpg",
      "alt": "The Polyamorous RomCom thumbnail"
    },
    "subtitle": "ft. Yung Gravy",
    "copy": "Comedy Central Digital sketch collaboration.",
    "youtubeId": "XhMz5vRlya8",
    "href": "https://www.youtube.com/watch?v=XhMz5vRlya8"
  },
  {
    "id": "remote-control-boss",
    "title": "Remote Control Boss",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/2PPkDxOul_0/hqdefault.jpg",
      "alt": "Remote Control Boss thumbnail"
    },
    "copy": "Comedy Central Digital character-driven sketch.",
    "youtubeId": "2PPkDxOul_0",
    "href": "https://www.youtube.com/watch?v=2PPkDxOul_0"
  },
  {
    "id": "litterbox-office",
    "title": "The Litterbox Office",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "viral"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/KIdN_iYBW7A/hqdefault.jpg",
      "alt": "The Litterbox Office thumbnail"
    },
    "copy": "500M+ views comedy concept.",
    "youtubeId": "KIdN_iYBW7A",
    "href": "https://www.youtube.com/watch?v=KIdN_iYBW7A"
  },
  {
    "id": "icontact",
    "title": "iContact",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/aQN6jBk_LWc/hqdefault.jpg",
      "alt": "iContact thumbnail"
    },
    "subtitle": "ft. DeStorm",
    "copy": "Comedy Central Digital collaboration.",
    "youtubeId": "aQN6jBk_LWc",
    "href": "https://www.youtube.com/watch?v=aQN6jBk_LWc"
  },
  {
    "id": "living-funeral-home",
    "title": "The Living Funeral Home",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/zcqkqql5VW0/hqdefault.jpg",
      "alt": "The Living Funeral Home thumbnail"
    },
    "subtitle": "ft. Lala Milan",
    "copy": "High-concept social comedy short.",
    "youtubeId": "zcqkqql5VW0",
    "href": "https://www.youtube.com/watch?v=zcqkqql5VW0"
  },
  {
    "id": "teen-uncle",
    "title": "Teen Uncle",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/YUJIjQ0MytM/hqdefault.jpg",
      "alt": "Teen Uncle thumbnail"
    },
    "subtitle": "ft. Adam Waheed",
    "copy": "Comedy Central Digital talent collaboration.",
    "youtubeId": "YUJIjQ0MytM",
    "href": "https://www.youtube.com/watch?v=YUJIjQ0MytM"
  },
  {
    "id": "whameo",
    "title": "Whameo",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-central",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/GBG1KLVBQPA/hqdefault.jpg",
      "alt": "Whameo thumbnail"
    },
    "subtitle": "ft. Sven Johnson",
    "copy": "Comedy Central Digital sketch piece.",
    "youtubeId": "GBG1KLVBQPA",
    "href": "https://www.youtube.com/watch?v=GBG1KLVBQPA"
  },
  {
    "id": "take-a-deep-breath",
    "title": "Take a Deep F***ing Breath",
    "roles": "Writer & Director",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/2Z4VgVKrveM/hqdefault.jpg",
      "alt": "Take a Deep F***ing Breath thumbnail"
    },
    "copy": "Comedy Central Originals short.",
    "youtubeId": "2Z4VgVKrveM",
    "href": "https://www.youtube.com/watch?v=2Z4VgVKrveM"
  },
  {
    "id": "freezing-your-eggs",
    "title": "Freezing Your Eggs",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/DJCgT1gw8nc/hqdefault.jpg",
      "alt": "Freezing Your Eggs thumbnail"
    },
    "copy": "Comedy Central Originals sketch.",
    "youtubeId": "DJCgT1gw8nc",
    "href": "https://www.youtube.com/watch?v=DJCgT1gw8nc"
  },
  {
    "id": "vesting-up",
    "title": "Vesting Up",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-central",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/gSojwTO5QZs/hqdefault.jpg",
      "alt": "Vesting Up thumbnail"
    },
    "copy": "Comedy Central Originals production.",
    "youtubeId": "gSojwTO5QZs",
    "href": "https://www.youtube.com/watch?v=gSojwTO5QZs"
  },
  {
    "id": "rich-friend",
    "title": "Rich Friend",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/lQankmO_xbQ/hqdefault.jpg",
      "alt": "Rich Friend thumbnail"
    },
    "subtitle": "ft. Anwar",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "lQankmO_xbQ",
    "href": "https://www.youtube.com/watch?v=lQankmO_xbQ"
  },
  {
    "id": "she-looks-like-her-dad",
    "title": "She Looks Like Her Dad",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/oCYzAHPMTUM/hqdefault.jpg",
      "alt": "She Looks Like Her Dad thumbnail"
    },
    "subtitle": "ft. DeStorm",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "oCYzAHPMTUM",
    "href": "https://www.youtube.com/watch?v=oCYzAHPMTUM"
  },
  {
    "id": "staying-young-forever",
    "title": "Staying Young Forever",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/bFYFLfq6nZo/hqdefault.jpg",
      "alt": "Staying Young Forever thumbnail"
    },
    "subtitle": "ft. Lala Milan",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "bFYFLfq6nZo",
    "href": "https://www.youtube.com/watch?v=bFYFLfq6nZo"
  },
  {
    "id": "nothing-gay-in-the-wild-west",
    "title": "Nothing Gay in the Wild West",
    "roles": "Director",
    "tags": [
      "comedy-central",
      "music-video"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/uE1Y7PHMdPc/hqdefault.jpg",
      "alt": "Nothing Gay in the Wild West thumbnail"
    },
    "subtitle": "ft. Brooks Allison",
    "copy": "Rose Kelso music video series.",
    "youtubeId": "uE1Y7PHMdPc",
    "href": "https://www.youtube.com/watch?v=uE1Y7PHMdPc"
  },
  {
    "id": "andys-roadshow",
    "title": "Andy's Roadshow",
    "roles": "Writer, Director, & Editor",
    "tags": [
      "comedy-sketches",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/iLNypL04zH0/hqdefault.jpg",
      "alt": "Andy's Roadshow thumbnail"
    },
    "copy": "Original sketch content.",
    "youtubeId": "iLNypL04zH0",
    "href": "https://www.youtube.com/watch?v=iLNypL04zH0"
  },
  {
    "id": "tuber",
    "title": "Tuber",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-sketches",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/0U5SCBko2XM/hqdefault.jpg",
      "alt": "Tuber thumbnail"
    },
    "copy": "Original sketch content.",
    "youtubeId": "0U5SCBko2XM",
    "href": "https://www.youtube.com/watch?v=0U5SCBko2XM"
  },
  {
    "id": "beauty-and-the-bowl",
    "title": "Beauty and the Bowl",
    "roles": "Director, Cinematographer, & Editor",
    "tags": [
      "comedy-sketches",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/RhzSqWrjx7Q/hqdefault.jpg",
      "alt": "Beauty and the Bowl thumbnail"
    },
    "subtitle": "ft. Uncle Function",
    "copy": "Sketch comedy featured on Funny Or Die.",
    "youtubeId": "RhzSqWrjx7Q",
    "href": "https://www.youtube.com/watch?v=RhzSqWrjx7Q"
  },
  {
    "id": "poly-bachelorette",
    "title": "Poly Bachelorette",
    "roles": "Writer, Director, DP, & Editor",
    "tags": [
      "comedy-sketches",
      "original"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/PEwfwxtwkWE/hqdefault.jpg",
      "alt": "Poly Bachelorette thumbnail"
    },
    "copy": "Original sketch content.",
    "youtubeId": "PEwfwxtwkWE",
    "href": "https://www.youtube.com/watch?v=PEwfwxtwkWE"
  },
  {
    "id": "grandmothers-announcement",
    "title": "Grandmother's Announcement",
    "roles": "Director, Cinematographer, & Editor",
    "tags": [
      "comedy-sketches",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/qSPdMoxsZoU/hqdefault.jpg",
      "alt": "Grandmother's Announcement thumbnail"
    },
    "copy": "Written by Lulu Krause.",
    "youtubeId": "qSPdMoxsZoU",
    "href": "https://www.youtube.com/watch?v=qSPdMoxsZoU"
  },
  {
    "id": "settling",
    "title": "Settling",
    "roles": "Co-Director, Cinematographer, & Editor",
    "tags": [
      "comedy-sketches",
      "collab"
    ],
    "media": {
      "kind": "image",
      "src": "https://i.ytimg.com/vi/qhXZjxXbW4s/hqdefault.jpg",
      "alt": "Settling thumbnail"
    },
    "copy": "Featuring Gianmarco Soresi & Megan Sass.",
    "youtubeId": "qhXZjxXbW4s",
    "href": "https://www.youtube.com/watch?v=qhXZjxXbW4s"
  }
];
