// Generated by scripts/gen-series.mjs. Do not edit directly.
import type { Series } from "./series";

export const SERIES: Series[] = [
  {
    "id": "Comedy-central",
    "title": "Comedy Central Digital",
    "description": "Series description coming soon.",
    "showOnHome": true,
    "homeOrder": 1
  },
  {
    "id": "Making-it",
    "title": "Making It",
    "description": "Series description coming soon.",
    "showOnHome": true,
    "homeOrder": 2
  },
  {
    "id": "Apocalypse-problems",
    "title": "Apocalypse Problems",
    "description": "Series description coming soon.",
    "showOnHome": true,
    "homeOrder": 3
  },
  {
    "id": "Asian-afterlife",
    "title": "Andy's Asian Afterlife",
    "description": "Series description coming soon.",
    "showOnHome": true,
    "homeOrder": 4
  }
];
